### ISSUE TITLE
CSS选择器

### ISSUE THREAD

**Issue by liangfengbo** [liangfengbo/study#1]
## 选择器：

- 元素选择器 p span{}
- 类选择器 .name
- ID选择器 #name
- 属性选择器 .select[type='username']
- 通配符选择器 * 
- 父子选择器 ul > li
- 兄弟选择器 li + div
- 伪类选择器 a:link,visited,hover,active
- 伪元素选择器 p:first-letter p:first-line  p:before p:after  p:first-child p:last-child p:nth-child(n)

## Tree

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>学习CSS选择器大全</title>
</head>
<body>
<div id="wrap">
  <ul class="box">
    <li class="item item-active"></li>
    <li class="item">
      <p>p</p>
      <p><span>p</span></p>
    </li>
    <li class="item"></li>
  </ul>
</div>
</body>
</html>
```

## ID选择器

```css
#wrap {
    background-color: red;
}
```

## 类选择器

```css
.box {
    color: #fff;
}
```

## 通配选择器，选择所有元素

```css
* {
    font-size: 14px;
}
```

## 元素选择器

```
li {
    display: inline-block;
}

p ~ ul {
    /*选择前面有 <p> 元素的每个 <ul> 元素。*/
}
```

## 声明分组

```css
div, ul, li {
    margin: 0;
    padding: 0;
}
```

## 后代选择器
```css
ul li {
    /*选择ul下的所有li元素*/
}
```

## 父子选择器

```css
ul > li {
    /*选择父元素为 <ul> 元素的所有 <li> 元素*/
}
```

## 相邻兄弟选择器

```css
li + div {
    /*选择紧接在 <li> 元素之后的所有 <div> 元素。*/
}
```

## 属性选择器

```css
a[target=_blank] {
    color: #fff;
    /*选择 target="_blank" 的所有元素。*/
}

a[title~=flower] {
    color: #fff;
    /*选择 title 属性包含单词 "flower" 的所有元素。*/
}

a[lang|=en] {
    color: #fff;
    /*选择 lang 属性值以 "en" 开头的所有元素。*/
}

a[src^="https"] {
    /*选择其 src 属性值以 "https" 开头的每个 <a> 元素。	*/
}

a[src$=".pdf"] {
    /*选择其 src 属性以 ".pdf" 结尾的所有 <a> 元素。*/
}

a[src*="abc"] {
    /*选择其 src 属性中包含 "abc" 子串的每个 <a> 元素。	*/
}
```

## 伪类选择器

```css
a:link {
    /*选择所有未被访问的链接。*/
}

a:visited {
    /*选择所有已被访问的链接。*/
}

a:active {
    /*选择活动链接。*/
}

a:hover {
    /*选择鼠标指针位于其上的链接。*/
}

input:focus {
    /*选择获得焦点的 input 元素。*/
}

p:lang(it){
    /*选择带有以 "it" 开头的 lang 属性值的每个 <p> 元素*/
}

p:first-child {
    /*选择属于父元素的第一个子元素的每个 <p> 元素*/
}

p:first-of-type {
    /*选择属于其父元素的首个 <p> 元素的每个 <p> 元素。*/
}

p:last-of-type {
    /*选择属于其父元素的最后 <p> 元素的每个 <p> 元素。*/
}

p:only-of-type {
    /*选择属于其父元素唯一的 <p> 元素的每个<p> 元素*/
}

p:only-child {
    /*选择属于其父元素的唯一子元素的每个 <p> 元素*/
}

p:nth-child(2) {
    /*选择属于其父元素的第二个子元素的每个 <p> 元素。*/
}

p:nth-child(2n) {
    /*选择属于其父元素的第2的倍数子元素的每个 <p> 元素。*/
}

p:nth-last-child(2) {
    /*同上，从最后一个子元素开始计数。*/
}

p:nth-of-type(2) {
    /*选择属于其父元素第二个 <p> 元素的每个 <p> 元素*/
}

p:nth-last-of-type(2){
    /*同上，但是从最后一个子元素开始计数。	*/
}

p:last-child {
    /*选择属于其父元素最后一个子元素每个 <p> 元素。	*/
}

:root{
    /*选择文档的根元素*/
}

p:empty{
    /*选择没有子元素的每个 <p> 元素（包括文本节点）。*/
}

#news:target{
    /*选择当前活动的 #news 元素。	*/
}

input:enabled{
    /*选择每个启用的 <input> 元素。*/
}

input:disabled{
    /*选择每个禁用的 <input> 元素	*/
}

input:checked{
    /*选择每个被选中的 <input> 元素。*/
}

:not(p){
    /*选择非 <p> 元素的每个元素。*/
}

::selection	{
    /*选择被用户选取的元素部分。*/
}
```

## 伪元素选择器

```css
p:first-letter {
    /*选择每个 <p> 元素的首字母*/
}

p:first-line {
    /*选择每个 <p> 元素的首行。*/
}

p:before {
    /*在每个 <p> 元素的内容之前插入内容。*/
}

p:after {
    /*在每个 <p> 元素的内容之后插入内容*/
}
```
